### ISSUE TITLE
data ops with multiple operands and the program counter

### ISSUE THREAD

**Issue by ksherlock** [marketideas/qasm#51]
I discovered (this feature is used in Marinetti) that Merlin 16+ updates the program counter after each operand of a data statement.

eg:

Merlin16:
```
                     2             ORG   0                                      
000000: 00 00 02 00  3             DW    *,*,*,*                                
000004: 04 00 06 00    
```

No other assembler that I tested (qasm (iigs), qasm(new), merlin32, orca/m, mpw asm iigs) update the program counter within the line.

qasm (iigs):
```
                     2              org  0            
000000: 00 00 00 00  3              dw   *,*,*,*      
000004: 00 00 00 00 
```

qasm(new):
```
00/0000:                 2                  org   0           
00/0000:00 00 00 00      3  %11             dw    *,*,*,*     
        00 00 00 00 
```

Merlin32:
```
    2 |  1 qasm.s      2 | Directive   | 11 |         |    0 | 00/8000               |             org   0              
    3 |  1 qasm.s      3 | Empty       | 11 |         |    0 | 00/0000               | ozunid_1                         
    4 |  1 qasm.s      3 | Data        | 11 |         |    8 | 00/0000 : 00 00 00 00 |             dw    ozunid_1,ozunid_1,ozunid_1,ozunid_1
      |                  |             |    |         |      |           00 00 00 00 |
    5 |  1 qasm.s      4 | Empty       | 11 |         |    0 | 00/0008               |                                  
------+------------------+-------------+----+---------+------+-----------------------+----------------------------------------------------------------------
```

mpw:
```
00000 0000                              test    proc
00000 0000 0000 0000 00                 start   dc.w *-start,*-start,*-start,*-start
00008 0008                                      endp
                                                end
```
orca/m:
```
0001 0000               
0002 0000              test           start 
0003 0000 00 00 00 00  start          dc i2'*-start,*-start,*-start,*-start' 
0004 0008                             end 
 
```

The Merlin 8/16 manual doesn't say anything either way about how it's supposed to work (just that `*` = "current value of PC").

Should QAsm follow Merlin 16+'s example? db/da/dw/adr/adrl/ddb are affected.

**Comment by lroathe** [comment]
We should follow Merlin16+'s example. Compatibility unless there is a compelling reason to not be.

**Comment by marketideas** [comment]
Thanks Kelvin.
These ring a bell that hasn't tolled for many, many years.  Can you run the same test source under Merlin 8 or regular 16 (not +) and see what happens?  Also,  did you try using different XC flags. None, XC, and XC/XC?
My feint memory is that different versions of Merlin did this differently

**Comment by ksherlock** [comment]
I tested Merlin-Pro 2.23 (Yegg-Men crack edition) and Merlin-16 3.44, with 0, 1, and 2 XCs. they all behaved the same in my testing.

![image](https://user-images.githubusercontent.com/964904/95703722-5aaffd00-0c1d-11eb-89c9-61fdf171c126.png)

![image](https://user-images.githubusercontent.com/964904/95704051-a498e300-0c1d-11eb-8229-d2eaa0403341.png)
